### ISSUE TITLE
Ensure all components are tested

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lux-design-system#121]
Components that have been brought over, have logic, and do not yet have tests
- [x] LuxInputButton
- [x] LuxLibraryHeader (Max)
- [x] LuxLibraryLogo

**Comment by maxkadel** [comment]
When I try to add the LuxLogoLibraryIcon to the styleguide, I get `SyntaxError: Unterminated template (1:3) (at acorn.mjs:3186:13)` and the icon does not display. 

I'm not sure where this issue is stemming from, it looks like the syntax of the file itself is correct, and does not include unclosed tags.

**Comment by kevinreiss** [comment]
Work in Progress: https://github.com/pulibrary/lux-styleguidist/pull/134

**Comment by maxkadel** [comment]
These components are now tested.
