### ISSUE TITLE
Create Upgrade Instructions to convert an application from Lux 4 to Lux 5 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lux-design-system#132]
- [x] Review changelog of approvals branch for lux-styleguidist
- [ ] Create a list of patterns that need to be replicated on other applications. 
- [ ] Update a Ruby on Rails application to use Lux.
- [ ] Update a Vue app to use Lux. (possible candidates: https://github.com/pulibrary/allsearch_frontend/, https://github.com/pulibrary/marquand-catalogs )
- [x] Upgrade a Ruby on Rails application that uses Lux to Lux 5. https://github.com/pulibrary/lux-styleguidist/issues/175

**Comment by kevinreiss** [comment]
Will discuss breaking this up with the LUX group tomorrow (4/10)

**Comment by sandbergja** [comment]
This is done!
