### ISSUE TITLE
Add semantic version to next to the LUX Styleguide in the Docs navigation column

### ISSUE THREAD

**Issue by sdellis** [pulibrary/lux-design-system#172]
It should look something like this ("4.5.7"):
![Screenshot 2024-03-29 at 2 04 45 PM](https://github.com/pulibrary/lux-styleguidist/assets/609368/0b5a66fb-26e9-484a-8b8b-0ad4282d1da7)

Currently the versioning is missing:
![Screenshot 2024-03-29 at 2 04 31 PM](https://github.com/pulibrary/lux-styleguidist/assets/609368/e866c1a5-a5ce-4c08-8d2a-0db3d4c60f17)

**Comment by sdellis** [comment]
Looks like you can do it here, but I think we will want this to auto update rather than hardcode:
https://vue-styleguidist.github.io/Configuration.html#version

**Comment by sandbergja** [comment]
Thanks for finding that documentation, @sdellis !  It looks like if we set `version` to `process.env.npm_package_version`, it automatically can pull it from the `package.json`.  I opened a pr to do that in #331
