### ISSUE TITLE
Resize LuxLibraryLogo

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lux-design-system#246]
### What maintenance needs to be done?
Make the LuxLibraryLogo match the sizes on https://library.psb-prod.princeton.edu/ 

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- In order to match the branding on the new site, we want the logo sizing to match

### Acceptance criteria
 - [ ] For similar media sizes (we may not have the same exact breakpoints) the logo should be a similar size on Lux and https://library.psb-prod.princeton.edu/

**Comment by christinach** [comment]
Fixed
