### ISSUE TITLE
Align the bottom-most "princeton university" logo with the right-most element of the header

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lux-design-system#307]
### Current display
![Screenshot 2024-08-05 at 9 13 21 AM](https://github.com/user-attachments/assets/c4dd17af-c312-40da-b089-dd9f3b5c557e)

### Desired display

Provide some consistency in right alignment to allow the header and footer to frame the page. maybe by pulling the princeton university logo further to the right.

(Note this is a departure from the new library site's footer, which doesn't have anything as far to the right as its header.)

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by christinach** [comment]
Currently the footer display is:
![Footer - screenshot](https://github.com/user-attachments/assets/1e63f944-48c0-4f6e-9408-d63a7e7814e3)

**Comment by christinach** [comment]
### Display of the Library website header and footer.

![Library website header and footer](https://github.com/user-attachments/assets/804432de-2492-457e-837e-ff035cab2726)

**Comment by hackartisan** [comment]
I've updated the title to clarify. look forward to discussing with the group.
