### ISSUE TITLE
Reduce bottom spacing on new footer

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lux-design-system#309]
### Current display
![Screenshot 2024-08-05 at 9 18 05 AM](https://github.com/user-attachments/assets/143462af-7376-4af7-b262-e26ecebdeb70)

### Desired display

![Screenshot 2024-08-05 at 9 17 56 AM](https://github.com/user-attachments/assets/707f0f23-4abc-408e-be0c-4cfd70e31a4d)

### Acceptance criteria

- [ ] Reduce the spacing below the bottom of the footer, as seen in example from new library website
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by christinach** [comment]
I'm currently working on this as part of #306 and as part of a general footer update.
