### ISSUE TITLE
Princeton university Library Logo should be smaller in smaller screens

### ISSUE THREAD

**Issue by christinach** [pulibrary/lux-design-system#344]
### Example display from the catalog

The PUL Logo displays large in the header and the footer  

![Princeton university Library Logo - Catalog Header and Footer](https://github.com/user-attachments/assets/92d46883-ea37-4c48-9aae-8ed39b9bc2b0)

### Example of PUL logo displaying smaller in the header
The Library Website has a better size of the PUL logo in the header
![Princeton University Library Logo - Library Website Header and footer](https://github.com/user-attachments/assets/8ea22cbb-e22a-4d95-bfb7-d50822dbd52d)

### Acceptance criteria
- [ ] PUL logo displays smaller and the same size in the header and the footer.
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by sdellis** [comment]
I have done some experiments in trying to use the LuxLibraryHeader. Not only should the logo be smaller, but the header also has additional margins and padding in it that make it unusable on some mobile viewports. 

Current screenshot:

<img width="376" alt="Screenshot 2024-11-05 at 1 29 22 PM" src="https://github.com/user-attachments/assets/d50fe648-269f-4404-974e-e13ddfa6cabf">


Here are my notes for fixing it. 

For mobile screens... (see screenshot below)

- lux-app-name should have `margin: 0`
- lux-header-content should have `padding: 0`
- lux-library-logo should have `marging: .5rem`
- svg img should be 205px wide and 40 high. 

<img width="343" alt="Screenshot 2024-11-05 at 1 28 42 PM" src="https://github.com/user-attachments/assets/7e70e83b-7e17-4e70-b91c-0be5efa6e286">

**Comment by vh8154** [comment]
Closed by #391
