### ISSUE TITLE
Separate "university footer" for broader use

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lux-design-system#360]
### User story
We agreed on the last mockup provided below in comments.

The top part of the new footer includes a lot of elements that are primarily relevant for the library website. We'd like to be able to just include the bottom part, but there a few things it needs to always have:

- privacy policy link
- accessibility link
- copyright statement
- copyright infringement link
- princeton university logo / link

### Acceptance criteria

- [ ] there's a lux component LuxUniversityFooter for dark or light mode
- [ ] the LuxLibraryFooter includes the new footer and any duplicate links are removed from it.
- [ ] If this change touches any of the files referenced in `.rubocop_todo.yml` create a new ticket to address the rubocop todo.
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by hackartisan** [comment]
Things that are required to be on every page:

- The princeton Logo
- copyright infringement
- accessibility link
- copyright statement
- privacy notice

all these except accessibility are on princeton.edu (it's higher up on that site)

Maybe re-write this ticket as a "campus footer" and "app footer" distinction.

**Comment by beth-german** [comment]
![image](https://github.com/user-attachments/assets/dcbb14a4-7519-4cf0-bc27-28521ac76da6)

**Comment by beth-german** [comment]
Nothing in the middle 

![image](https://github.com/user-attachments/assets/e74b0892-439f-4954-bc9a-de14e870b3fd)

**Comment by beth-german** [comment]
Reverse 
![image](https://github.com/user-attachments/assets/da90b6ef-3820-45e5-b986-9f02f580ad80)

**Comment by beth-german** [comment]
![image](https://github.com/user-attachments/assets/d3ae1bdf-8a10-4404-af3e-fc77de508e57)

**Comment by hackartisan** [comment]
@beth-german these are great!

**Comment by christinach** [comment]
See further discussion in [slack lux channel](https://pulibrary.slack.com/archives/C061HHABWGM/p1728675807468229)

**Comment by beth-german** [comment]
Matthew suggests using this link for the copyright link in the footer: https://library.princeton.edu/about/policies/copyright-and-permissions-policies

**Comment by hackartisan** [comment]
@beth-german should we call the link something other than "Copyright Infringement"? Like maybe "Copyright policy"?

**Comment by beth-german** [comment]
"Library Copyright Policy" or "Copyright Policy"?

**Comment by hackartisan** [comment]
I think it's clear it's the library policy if you follow the link, probably the shorter version is okay.
