### ISSUE TITLE
Add Icon instructions to the styleguide

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lux-design-system#380]
### User story

As a lux contributor, I want to know how to add a new icon to lux.

### Acceptance criteria

- [ ] There is a section in the styleguide that includes this information from the old lux repository: https://github.com/pulibrary/lux/blob/ac5d0fcee436fb03ad9a88a84629e911aba0250b/docs/adding-icons.md ([here's how it looked in the old lux styleguide](https://pulibrary.github.io/lux/docs/#/Adding%20Icons))
- [ ] I can successfully use the new Adding Icons section with Voice Over in Safari.
- [ ] I have checked this section using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Implementation notes, if any

* [This vue-styleguidist documentation](https://vue-styleguidist.github.io/docs/Components.html#sections) has an example of a styleguide section that gets its content from a markdown file.

**Comment by sdellis** [comment]
@ishasinha1 and @sandbergja, can this ticket be closed?
