### ISSUE TITLE
Recent change to logo svg sizing breaks the LuxLibraryFooter

### ISSUE THREAD

**Issue by sdellis** [pulibrary/lux-design-system#401]
In short, the PUL logo is not being sized correctly in the Library Footer after recent changes resulting in v6.0.0. 

### Expected behavior
The logo should be smaller and prevent the phone number from running into the University Footer policy links below it. 

### Actual behavior
See the screenshot included in this ticket: https://github.com/pulibrary/imagecat-rails/pull/267#pullrequestreview-2474058051

### Steps to replicate
The oversized logo is visible in the Styleguide, although the phone number doesn't overlap like it does in imagecat.

### Impact of this bug
The imagecat upgrade ticket mentioned above is blocked until resolved.

### Acceptance criteria
- [ ] If this change touches any of the files referenced in `.rubocop_todo.yml` create a new ticket to address the rubocop  todo.

### Implementation notes, if any
Any other components that use the LuxLibraryLogo will be affected due to the changes in the way we size that SVG image. Perhaps worth an implementation note for SVG image sizing going forward.

**Comment by christinach** [comment]
@sdellis this ticket seems to be resolved. I'm checking https://imagecat-staging.princeton.edu/ 
Can I close it? 

I've created a new one for the [logo size between footer and header](https://github.com/pulibrary/lux-design-system/issues/405).
